### ISSUE TITLE
Failed to load url cheerio (resolved id: cheerio) 

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [gvkhna/astro-media#1]
i can't run it do i need also astro-image ? 

```
🏃 [start] Running command "astro dev"
Failed to load url cheerio (resolved id: cheerio) in /home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts. Does the file exist?
02:38:45 [vite] Error when evaluating SSR module /node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts: failed to import "cheerio"
|- Error: Cannot find module 'cheerio' imported from '/home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts'
    at nodeImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55873:25)
    at ssrImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55775:30)
    at eval (eval at instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55834:28), <anonymous>:4:37)
    at async instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55837:9)

02:38:45 [vite] Error when evaluating SSR module /node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/index.ts: failed to import "/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts"
|- Error: Cannot find module 'cheerio' imported from '/home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts'
    at nodeImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55873:25)
    at ssrImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55775:30)
    at eval (eval at instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55834:28), <anonymous>:4:37)
    at async instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55837:9)

02:38:45 [vite] Error when evaluating SSR module /home/manjaro/DEV/uno test/marina copie/astro.config.mjs: failed to import "/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/index.ts"
|- Error: Cannot find module 'cheerio' imported from '/home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts'
    at nodeImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55873:25)
    at ssrImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55775:30)
    at eval (eval at instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55834:28), <anonymous>:4:37)
    at async instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55837:9)

02:38:45 [astro] Unable to load /home/manjaro/DEV/uno test/marina copie/astro.config.mjs

 error   Cannot find module 'cheerio' imported from '/home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts'
Error: Cannot find module 'cheerio' imported from '/home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro-media@0.0.27_sharp@0.32.1/node_modules/astro-media/integration/lib/get-image.ts'
    at nodeImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55873:25)
    at ssrImport (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55775:30)
    at eval (eval at instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55834:28), <anonymous>:4:37)
    at async instantiateModule (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:55837:9)

 error   Cannot read properties of undefined (reading 'map')
  File:
    /home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/events/error.js:21:34
  Code:
    20 |     cliCommand: cmd,
    > 21 |     configErrorPaths: err.issues.map((issue) => issue.path.join("."))
         |                                  ^
      22 |   };
      23 |   return [{ eventName: EVENT_ERROR, payload }];
      24 | }
  Stacktrace:
TypeError: Cannot read properties of undefined (reading 'map')
    at eventConfigError (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/events/error.js:21:34)
    at handleConfigError (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:126:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:192:5
    at async runCommand (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:186:76)
    at async cli (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:260:5)

❌ [start] Failed with exit status 1
```

**Comment by jojojojojoj5564656465465** [comment]
I tried this config


```js
import sitemap from '@astrojs/sitemap'
import critters from 'astro-critters'
import robotsTxt from 'astro-robots-txt'
import { defineConfig } from 'astro/config'
import UnoCSS from 'unocss/astro'
import compress from 'astro-compress'
import lightningcss from 'vite-plugin-lightningcss'
import cloudflare from '@astrojs/cloudflare'
import mdx from '@astrojs/mdx'

// https://astro.build/config

// https://astro.build/config
import image from '@astrojs/image'

// https://astro.build/config
import media from 'astro-media/integration'
// https://astro.build/config
export default defineConfig({
	output: 'server',
	adapter: cloudflare({ mode: 'directory' }),
	server: {
		host: '0.0.0.0'
	},
	site: 'https://massage-kobido-lifting.com/',
	integrations: [
		media(),
		image({
			// serviceEntryPoint: '@astrojs/image/sharp'
		}),
		critters(),
		compress(),
		UnoCSS({
			injectReset: true
		}),
		lightningcss({
			browserslist: '>= 0.25%'
		}),
		sitemap(),
		robotsTxt(),
		mdx({
			commonmark: true
		})
	]
})
```

**Comment by gvkhna** [comment]
Your config looks correct. Cheerio is part of the devDependencies, not sure why it's not installed but run npm install cheerio?

**Comment by jojojojojoj5564656465465** [comment]
Does your software works with cloudflair adapter? Do I need use astro image as well? Sent from Android deviceLe 7 juil. 2023 03:07, Gaurav Khanna ***@***.***> a écrit :
Your config looks correct. Cheerio is part of the devDependencies, not sure why it's not installed but run npm install cheerio?

**Comment by gvkhna** [comment]
I don't believe so. It only works with node/sharp. No you shouldn't need to use astro image, this is a replacement. I'm not familiar with cloudflare adapter so if this doesn't work for you I can perhaps take a look otherwise I would recommend sticking with astro-image.

**Comment by jojojojojoj5564656465465** [comment]
> Your config looks correct. Cheerio is part of the devDependencies, not sure why it's not installed but run npm install cheerio?

I have new error :+1: 

```
  Cannot find module 'node_modules/astro-media/integration/endpoint'
  Require stack:
  - /home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/routing/manifest/create.js
Error: Cannot find module 'node_modules/astro-media/integration/endpoint'
Require stack:
- /home/manjaro/DEV/uno test/marina copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/routing/manifest/create.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Function.resolve (node:internal/modules/helpers:125:19)
    at injectedRouteToItem (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/routing/manifest/create.js:119:29)
    at file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/routing/manifest/create.js:251:59
    at Array.sort (<anonymous>)
    at createRouteManifest (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/routing/manifest/create.js:248:56)
    at configureServer (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/vite-plugin-astro-server/plugin.js:18:22)
    at _createServer (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/vite@4.4.1/node_modules/vite/dist/node/chunks/dep-439026c8.js:65002:30)
    at async createContainer (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/dev/container.js:45:22)
    at async createContainerWithAutomaticRestart (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/dev/restart.js:90:28)
    at async dev (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/core/dev/dev.js:33:19)
    at async runCommand (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:204:7)
    at async cli (file:///home/manjaro/DEV/uno%20test/marina%20copie/node_modules/.pnpm/astro@2.8.0_sharp@0.32.1/node_modules/astro/dist/cli/index.js:260:5)
❌ [start] Failed with exit status 1
```

**Comment by jojojojojoj5564656465465** [comment]
My bad !

You have to do pnpm i -D cheerio 
Remove astro-image is mandatory

**Comment by gvkhna** [comment]
That’s great to hear, thank you for your feedback. Next time I have a chance I’ll look into resolving this cheerio issue. Perhaps moving it out of devDependencies will solve the issue. 

Also yes it makes sense it conflicts with Astro-image. I don’t have much incentive to make them work together.
